### ISSUE TITLE
deploy_master is failing on a typescript error 

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa#5159]
This has been failing for a while, I think since https://github.com/mozilla/fxa/commit/4b9b2624158c13e1b3828b0b5d7635283b8f0737 landed.

https://164996-36831081-gh.circle-artifacts.com/0/artifacts/fxa-builder.log

#10 633.9 fxa-auth-server: ../fxa-shared/l10n/localizeTimestamp.ts(5,33): error TS7016: Could not find a declaration file for module 'accept-language'. '/fxa/packages/fxa-shared/node_modules/accept-language/index.js' implicitly has an 'any' type.
#10 633.9 fxa-auth-server:   Try `npm install @types/accept-language` if it exists or add a new declaration (.d.ts) file containing `declare module 'accept-language';`
#10 633.9 fxa-auth-server: npm ERR! code ELIFECYCLE
#10 633.9 fxa-auth-server: npm ERR! errno 2
#10 633.9 fxa-auth-server: npm ERR! fxa-auth-server@1.168.2 build: `NODE_ENV=dev npm run gen-keys && tsc`

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1790)
┆Issue Number: FXA-1790

**Comment by jrgm** [comment]
Closing as duplicate of https://github.com/mozilla/fxa/issues/5150
